# Generated by Django 5.2.4 on 2025-07-07 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('address', models.TextField(blank=True)),
                ('tax_id', models.CharField(help_text="Client's Tax Identification Number", max_length=20, unique=True)),
                ('dues', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('previous_dues', models.DecimalField(decimal_places=2, default=0.0, help_text='Dues carried over from previous records', max_digits=10)),
                ('registration_date', models.DateField(auto_now_add=True)),
                ('last_payment_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional tax or client notes')),
            ],
        ),
    ]
