# Generated by Django 5.2.4 on 2025-07-07 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid')], default='Pending', max_length=10)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, help_text='Details about the dues (e.g., tax type or period)')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dues_records', to='clients.client')),
            ],
        ),
    ]
