# Generated by Django 5.2.4 on 2025-07-07 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_dues'),
    ]

    operations = [
        migrations.AddField(
            model_name='dues',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='dues',
            name='remaining_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='dues',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Partially Paid', 'Partially Paid'), ('Paid', 'Paid')], default='Pending', max_length=15),
        ),
    ]
