# Generated by Django 5.2.4 on 2025-07-07 10:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_dues_paid_amount_dues_remaining_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='registration_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
