# Generated by Django 5.2.4 on 2025-07-07 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_alter_client_email_alter_client_registration_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='dues',
        ),
        migrations.RemoveField(
            model_name='client',
            name='previous_dues',
        ),
    ]
